# Build-time генерация component_allowlist.h (документ п. 19/29/53).
# Хеши SHA-256 собственных скриптов SCU вшиваются в ScannerCore как константы.
# Список файлов здесь должен совпадать со списком Assets в SCU.App.csproj.

set(ALLOWLIST_FILES "SCU.ps1;Utilities.bat")

set(HEADER "#pragma once\n")
string(APPEND HEADER "// Generated by cmake/component_allowlist.cmake — do not edit.\n")
string(APPEND HEADER "// SHA-256 (hex, lowercase) of SCU's own scripts at build time.\n")
string(APPEND HEADER "#include <cstddef>\n\n")
string(APPEND HEADER "inline constexpr size_t kAllowlistEntryCount = 2;\n")
string(APPEND HEADER "inline const char* const kAllowlistSha256[kAllowlistEntryCount] = {\n")

set(index 0)
foreach(name IN LISTS ALLOWLIST_FILES)
    file(SHA256 "${ASSETS_DIR}/${name}" hash)
    math(EXPR index "${index} + 1")
    string(APPEND HEADER "    \"${hash}\", // ${name}\n")
endforeach()
string(APPEND HEADER "};\n")

file(WRITE "${OUT_FILE}" "${HEADER}")
