# Генерация signing_pin.h: отпечаток сертификата подписи (SHA-1) вшивается
# в ScannerCore как константа. Если signing\thumbprint.txt отсутствует —
# пин пустой (dev-режим: self-integrity warn-only по --dev-unsigned-ok).
# Новый сертификат = новый thumbprint.txt = автоматический перепиннинг.

set(PIN_FILE "${PIN_FILE}")
set(PIN_VALUE "")

if (PIN_FILE STREQUAL "")
    message(FATAL_ERROR "signing_pin.cmake: PIN_FILE (-DPIN_FILE=...) is required — в скрипт-режиме CMAKE_CURRENT_SOURCE_DIR недоступен")
endif()

if (EXISTS "${PIN_FILE}")
    file(READ "${PIN_FILE}" PIN_VALUE)
    string(STRIP "${PIN_VALUE}" PIN_VALUE)
    # CMake-регулярки не поддерживают квантификатор {40}: проверяем длину и алфавит.
    string(LENGTH "${PIN_VALUE}" PIN_LENGTH)
    string(REGEX MATCH "^[0-9a-fA-F]+$" PIN_ALPHABET "${PIN_VALUE}")
    if (PIN_LENGTH EQUAL 40 AND PIN_ALPHABET)
        string(TOUPPER "${PIN_VALUE}" PIN_VALUE)
    else()
        message(WARNING "signing/thumbprint.txt: ожидался SHA-1 отпечаток (40 hex), получено '${PIN_VALUE}' — пин отключён")
        set(PIN_VALUE "")
    endif()
endif()

string(TOUPPER "${PIN_VALUE}" PIN_VALUE)

set(HEADER "#pragma once\n")
string(APPEND HEADER "// Generated by cmake/signing_pin.cmake — do not edit.\n")
string(APPEND HEADER "// SHA-1 thumbprint сертификата подписи; пустая строка = dev-сборка без пина.\n")
string(APPEND HEADER "#include <cstddef>\n\n")
if (PIN_VALUE STREQUAL "")
    string(APPEND HEADER "inline const char* const kSigningCertSha1 = \"\";\n")
else()
    string(APPEND HEADER "inline const char* const kSigningCertSha1 = \"${PIN_VALUE}\";\n")
endif()

file(WRITE "${OUT_FILE}" "${HEADER}")
